### PR TITLE
Added possibility login as superusers

### PR DESCRIPTION
**Pull request by WarmongeR1**
Added option CAN_LOGIN_IN_SUPERUSER
If CAN_LOGIN_IN_SUPERUSER == True -> you can login as in superuser
If CAN_LOGIN_IN_SUPERUSER == False -> you can't login as in superuser
By default you can't

### CODE REVIEW

**Comment by skorokithakis** [comment]
Thank you for the PR! However, this is already possible and described in the README:

~~~
CAN_LOGIN_AS = lambda request, target_user: request.user.is_superuser and not target_user.is_superuser
~~~

**Comment by WarmongeR1** [comment]
Yes, but we have lines before this Lambda

```python
if user.is_superuser:
        messages.error(request, _("You cannot log in as superusers."),
                       extra_tags=la_settings.MESSAGE_EXTRA_TAGS)
        return redirect(request.META.get("HTTP_REFERER", "/"))
```
https://github.com/skorokithakis/django-loginas/blob/master/loginas/views.py#L62

And If target user is superuser then we have error and redirect

```python
return redirect(request.META.get("HTTP_REFERER", "/"))
```

**Comment by skorokithakis** [comment]
Oh, that's a mistake, can you remove that completely?

**Comment by WarmongeR1** [comment]
I removed this condition and my option

**Comment by skorokithakis** [comment]
Looks great, thanks!

**Pull request merged**
