### PR TITLE
Fixes "null value in column `user_id`" when switching back to original user

### PR DESCRIPTION
**Pull request by theunraveler**
It seems that https://github.com/skorokithakis/django-loginas/pull/76 introduced a bug when switching back to your original user (at least when using `loginas.utils.restore_original_login` in a custom logout view).

This fix only logs a message if there is an original user ID. I figured that it isn't quite so relevant to log when a user switches back to their original user.

### CODE REVIEW

**Comment by skorokithakis** [comment]
Thanks for the PR! Could you leave a small comment in the `if` check to mention the circumstances in which the check might be `False`? This is just to document better why the check is needed.

**Comment by skorokithakis** [comment]
I've also fixed the tests enough that `master` now fails on the error your PR fixes. As a result, tests on your PR should now pass. Thanks!

**Comment by skorokithakis** [comment]
Actually I will merge this and see, thanks.

**Comment by theunraveler** [comment]
Thanks for the quick attention!

Looks like the tests passed, but the travis build failed because of a callback or something? Need anything else from me here?

**Pull request merged**
